backend:
  name: github
  repo: apostrafo/cdoaas
  app_id: Ov23liHXwzadGRhXBw2y
  branch: main
  auth_endpoint: auth
  api_root: https://api.github.com
  cms_label_prefix: netlify-cms/
  commit_messages:
    create: "Create {{collection}} \"{{slug}}\""
    update: "Update {{collection}} \"{{slug}}\""
    delete: "Delete {{collection}} \"{{slug}}\""

# Media ir viešas kelias
media_folder: "public/uploads"
public_folder: "/uploads"

# Publikuoti režimas
publish_mode: editorial_workflow

# Daugiakalbystės konfigūracija
i18n:
  structure: multiple_folders
  locales: [lt, en]
  default_locale: lt

# Kolekcijos
collections:
  # Bendros puslapių kolekcijos (files)
  - name: "pages"
    label: "Puslapiai"
    files:
      - file: "content/index.md"
        label: "Pagrindinis"
        name: "home"
        i18n: true
        fields:
          - {label: "Pavadinimas", name: "title", widget: "string", i18n: true}
          - {label: "Poraštė", name: "subtitle", widget: "string", i18n: true}
          - {label: "Turinys", name: "body", widget: "markdown", i18n: true}
      
      - file: "content/about.md"
        label: "Apie mus"
        name: "about"
        i18n: true
        fields:
          - {label: "Pavadinimas", name: "title", widget: "string", i18n: true}
          - {label: "Poraštė", name: "subtitle", widget: "string", i18n: true}
          - {label: "Turinys", name: "body", widget: "markdown", i18n: true}
      
      - file: "content/services.md"
        label: "Paslaugos"
        name: "services"
        i18n: true
        fields:
          - {label: "Pavadinimas", name: "title", widget: "string", i18n: true}
          - {label: "Poraštė", name: "subtitle", widget: "string", i18n: true}
          - {label: "Turinys", name: "body", widget: "markdown", i18n: true}
      
      - file: "content/approach.md"
        label: "Mūsų požiūris"
        name: "approach"
        i18n: true
        fields:
          - {label: "Pavadinimas", name: "title", widget: "string", i18n: true}
          - {label: "Poraštė", name: "subtitle", widget: "string", i18n: true}
          - {label: "Turinys", name: "body", widget: "markdown", i18n: true}
          
      - file: "content/case-studies.md"
        label: "Sėkmės istorijos"
        name: "case-studies"
        i18n: true
        fields:
          - {label: "Pavadinimas", name: "title", widget: "string", i18n: true}
          - {label: "Poraštė", name: "subtitle", widget: "string", i18n: true}
          - {label: "Turinys", name: "body", widget: "markdown", i18n: true}
          
      - file: "content/tools.md"
        label: "Įrankiai"
        name: "tools"
        i18n: true
        fields:
          - {label: "Pavadinimas", name: "title", widget: "string", i18n: true}
          - {label: "Poraštė", name: "subtitle", widget: "string", i18n: true}
          - {label: "Turinys", name: "body", widget: "markdown", i18n: true}
          
      - file: "content/contact.md"
        label: "Kontaktai"
        name: "contact"
        i18n: true
        fields:
          - {label: "Pavadinimas", name: "title", widget: "string", i18n: true}
          - {label: "Poraštė", name: "subtitle", widget: "string", i18n: true}
          - {label: "Turinys", name: "body", widget: "markdown", i18n: true}

  # Blog kolekcija (folder)
  - name: "blog"
    label: "Blogas"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - {label: "Pavadinimas", name: "title", widget: "string", i18n: true}
      - {label: "Data", name: "date", widget: "datetime", i18n: true}
      - {label: "Autorius", name: "author", widget: "string", i18n: true}
      - {label: "Nuotrauka", name: "image", widget: "image", i18n: true}
      - {label: "Trumpas aprašymas", name: "excerpt", widget: "text", i18n: true}
      - {label: "Turinys", name: "body", widget: "markdown", i18n: true}

  # Komandos narių kolekcija (folder)
  - name: "team"
    label: "Komanda"
    folder: "src/content/team"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - {label: "Vardas Pavardė", name: "name", widget: "string", i18n: true}
      - {label: "Pareigos", name: "position", widget: "string", i18n: true}
      - {label: "Nuotrauka", name: "photo", widget: "image", i18n: true}
      - {label: "LinkedIn", name: "linkedin", widget: "string", required: false, i18n: true}
      - {label: "Bio", name: "bio", widget: "text", i18n: true}
      - {label: "Eilės tvarka", name: "order", widget: "number", i18n: true}

  # Nustatymų kolekcija (files)
  - name: "settings"
    label: "Nustatymai"
    files:
      - file: "src/content/settings/navigation.md"
        label: "Navigacija"
        name: "navigation"
        i18n: true
        fields:
          - label: "Pagrindinis meniu"
            name: "main"
            widget: "list"
            i18n: true
            fields:
              - {label: "Pavadinimas", name: "label", widget: "string", i18n: true}
              - {label: "URL", name: "url", widget: "string", i18n: true}
      
      - file: "src/content/settings/site.md"
        label: "Svetainės informacija"
        name: "site"
        i18n: true
        fields:
          - {label: "Svetainės pavadinimas", name: "title", widget: "string", i18n: true}
          - {label: "Aprašymas", name: "description", widget: "text", i18n: true}
          - {label: "El. paštas", name: "email", widget: "string", i18n: true}
          - {label: "Telefonas", name: "phone", widget: "string", i18n: true} 