[build]
  publish = "dist"
  command = "npm run build"

# Handle 404 errors by serving the 404.html page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Handle SPA routing - redirect all paths to index.html and let client-side routing handle it
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 