[build]
  publish = "dist"
  command = "npm run build"

# Enable Netlify Visual Editor
[visual]
  framework = "astro"
  devCommand = "npm run dev"

# Handle 404 errors by serving the 404.html page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Exclude /admin path from SPA routing
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

# Handle SPA routing - redirect all paths to index.html and let client-side routing handle it
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 