backend:
  name: github
  repo: apostrafo/cdoaas
  branch: main
  auth_type: implicit
  auth_endpoint: https://github.com/login/oauth/authorize
  app_id: # Reikia įkelti GitHub OAuth App ID

# Media ir viešas kelias
media_folder: "public/uploads"
public_folder: "/uploads"

# Publikuoti režimas (redaktoriui būtina patvirtinti prieš pakeitimų publikavimą)
publish_mode: editorial_workflow

# Daugiakalbystės konfigūracija
i18n:
  # Pagrindinė (numatytoji) kalba
  default_locale: lt
  # Palaikomos kalbos
  locales: [lt, en]
  # Lauko vertimų lokalizavimo strategija
  localization:
    allow_global_fallback: true
    allow_field_fallback: true

# Kolekcijos
collections:
  # Bendros puslapių kolekcijos
  - name: "pages"
    label: "Puslapiai"
    files:
      - name: "home"
        label: "Pagrindinis puslapis"
        file: "content/index.md"
        i18n: true
        fields:
          - {label: "Antraštė", name: "title", widget: "string", i18n: true}
          - {label: "Poraštė", name: "subtitle", widget: "string", i18n: true}
          - {label: "Turinys", name: "body", widget: "markdown", i18n: true}

      - name: "about"
        label: "Apie mus"
        file: "src/content/about/about.md"
        i18n: true
        fields:
          - {label: "Antraštė", name: "title", widget: "string", i18n: true}
          - {label: "Turinys", name: "body", widget: "markdown", i18n: true}

      - name: "services"
        label: "Paslaugos"
        file: "src/content/services/services.md"
        i18n: true
        fields:
          - {label: "Antraštė", name: "title", widget: "string", i18n: true}
          - {label: "Poraštė", name: "subtitle", widget: "string", i18n: true}
          - {label: "Turinys", name: "body", widget: "markdown", i18n: true}

      - name: "approach"
        label: "Mūsų požiūris"
        file: "src/content/approach/approach.md"
        i18n: true
        fields:
          - {label: "Antraštė", name: "title", widget: "string", i18n: true}
          - {label: "Poraštė", name: "subtitle", widget: "string", i18n: true}
          - {label: "Turinys", name: "body", widget: "markdown", i18n: true}

      - name: "case-studies"
        label: "Praktiniai pavyzdžiai"
        file: "src/content/case-studies/case-studies.md"
        i18n: true
        fields:
          - {label: "Antraštė", name: "title", widget: "string", i18n: true}
          - {label: "Poraštė", name: "subtitle", widget: "string", i18n: true}
          - {label: "Turinys", name: "body", widget: "markdown", i18n: true}
          - label: "Praktiniai pavyzdžiai"
            name: "cases"
            widget: "list"
            i18n: true
            fields:
              - {label: "Pavadinimas", name: "name", widget: "string", i18n: true}
              - {label: "Logotipas", name: "logo", widget: "image", i18n: true, required: false}
              - {label: "Aprašymas", name: "description", widget: "text", i18n: true}
              - {label: "Iššūkiai", name: "challenges", widget: "text", i18n: true}
              - {label: "Sprendimai", name: "solutions", widget: "text", i18n: true}
              - {label: "Rezultatai", name: "results", widget: "text", i18n: true}

      - name: "tools"
        label: "Įrankiai"
        file: "src/content/tools/tools.md"
        i18n: true
        fields:
          - {label: "Antraštė", name: "title", widget: "string", i18n: true}
          - {label: "Poraštė", name: "subtitle", widget: "string", i18n: true}
          - {label: "Turinys", name: "body", widget: "markdown", i18n: true}
          - label: "Įrankiai"
            name: "tools"
            widget: "list"
            i18n: true
            fields:
              - {label: "Pavadinimas", name: "name", widget: "string", i18n: true}
              - {label: "Kategorija", name: "category", widget: "string", i18n: true}
              - {label: "Aprašymas", name: "description", widget: "text", i18n: true}
              - {label: "Ikonos pavadinimas", name: "icon", widget: "string", i18n: false, required: false}
              - {label: "URL", name: "url", widget: "string", i18n: false, required: false}

      - name: "contact"
        label: "Kontaktai"
        file: "src/content/contact/contact.md"
        i18n: true
        fields:
          - {label: "Antraštė", name: "title", widget: "string", i18n: true}
          - {label: "Poraštė", name: "subtitle", widget: "string", i18n: true, required: false}
          - {label: "Adresas", name: "address", widget: "text", i18n: true, required: false}
          - {label: "El. paštas", name: "email", widget: "string", i18n: false, required: false}
          - {label: "Telefonas", name: "phone", widget: "string", i18n: false, required: false}
          - {label: "Formos antraštė", name: "form_title", widget: "string", i18n: true, required: false}
          - {label: "Formos poraštė", name: "form_subtitle", widget: "text", i18n: true, required: false}
          - {label: "Turinys", name: "body", widget: "markdown", i18n: true}

  # Blog kolekcija
  - name: "blog"
    label: "Blog įrašai"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}{{language_suffix}}"
    i18n: true
    fields:
      - {label: "Antraštė", name: "title", widget: "string", i18n: true}
      - {label: "Data", name: "date", widget: "datetime", i18n: false}
      - {label: "Autorius", name: "author", widget: "string", i18n: false}
      - {label: "Paveikslėlis", name: "image", widget: "image", i18n: true, required: false}
      - {label: "Santrauka", name: "excerpt", widget: "text", i18n: true}
      - {label: "Turinys", name: "body", widget: "markdown", i18n: true}

  # Kitos atskirtos kolekcijos
  - name: "team"
    label: "Komandos nariai"
    folder: "src/content/team"
    create: true
    i18n: true
    fields:
      - {label: "Vardas", name: "name", widget: "string", i18n: false}
      - {label: "Pareigos", name: "position", widget: "string", i18n: true}
      - {label: "Nuotrauka", name: "photo", widget: "image", i18n: false}
      - {label: "LinkedIn", name: "linkedin", widget: "string", i18n: false, required: false}
      - {label: "Aprašymas", name: "bio", widget: "text", i18n: true}
      - {label: "Rodymo eilė", name: "order", widget: "number", i18n: false}

  # Nustatymų kolekcija
  - name: "settings"
    label: "Nustatymai"
    files:
      - name: "navigation"
        label: "Navigacija"
        file: "content/settings/navigation.yml"
        i18n: true
        fields:
          - label: "Pagrindinė navigacija"
            name: "main"
            widget: "list"
            i18n: true
            fields:
              - {label: "Etiketė", name: "label", widget: "string", i18n: true}
              - {label: "URL", name: "url", widget: "string", i18n: false}

      - name: "site"
        label: "Svetainės informacija"
        file: "content/settings/site.yml"
        i18n: true
        fields:
          - {label: "Svetainės pavadinimas", name: "title", widget: "string", i18n: true}
          - {label: "Aprašymas", name: "description", widget: "text", i18n: true}
          - {label: "Pagrindinis el. paštas", name: "email", widget: "string", i18n: false}
          - {label: "Telefonas", name: "phone", widget: "string", i18n: false} 